subjects = [
    'S01 Coal, lignite, and peat',
    'S02 Petroleum',
    'S03 Natural gas',
    'S04 Oil shales and tar sands',
    'S07 Isotopes and radiation sources',
    'S08 Hydrogen',
    'S09 Biomass fuels',
    'S10 Synthetic fuels',
    'S11 Nuclear fuel cycle and fuel materials',
    'S12 Management of radioactive wastes, and non-radioactive wastes from nuclear facilities',
    'S13 Hydro energy',
    'S14 Solar energy',
    'S15 Geothermal energy',
    'S16 Tidal and wave power',
    'S17 Wind energy',
    'S20 Fossil-fueled power plants',
    'S21 Specific nuclear reactors and associated plants',
    'S22 General studies of nuclear reactors',
    'S24 Power transmission and distribution',
    'S25 Energy storage',
    'S29 Energy planning, policy and economy',
    'S30 Direct energy conversion',
    'S32 Energy conservation, consumption, and utilization',
    'S33 Advanced propulsion systems',
    'S36 Materials science',
    'S37 Inorganic, organic, physical and analytical chemistry',
    'S38 Radiation chemistry, radiochemistry and nuclear chemistry',
    'S42 Engineering',
    'S43 Particle accelerators',
    'S46 Instrumentation related to nuclear science and technology',
    'S47 Other instrumentation',
    'S54 Environmental sciences',
    'S58 Geosciences',
    'S60 Applied life sciences',
    'S61 Radiation protection and dosimetry',
    'S62 Radiology and nuclear medicine',
    'S63 Radiation, thermal, and other environmental pollutant effects on living organisms and biological materials',
    'S70 Plasma physics and fusion technology',
    'S71 Classical and quantum mechanics, general physics',
    'S72 Physics of elementary particles and fields',
    'S73 Nuclear physics and radiation physics',
    'S74 Atomic and molecular physics',
    'S75 Condensed matter physics, superconductivity and superfluidity',
    'S77 Nanoscience and nanotechnology',
    'S79 Astrophysics, cosmology and astronomy',
    'S96 Knowledge management and preservation',
    'S97 Mathematical methods and computing',
    'S98 Nuclear disarmament, safeguards and physical protection',
    'S99 General and miscellaneous',
    ]
