import sys

CFG_SITE_LANGS = ["en"]

CFG_SITE_NAME = "INIS Input Management"
CFG_SITE_NAME_INTL = {
    "en": CFG_SITE_NAME
}

DEPOSIT_TYPES = [
    "inis.modules.deposit.workflows.upload:upload",
]

PACKAGES = [
    "inis.base",
    "inis.demosite",
    "inis.modules.deposit",
    "invenio.modules.*",
    "invenio.base",
]

try:
    from inis import instance_config
    sys.modules[__name__] = instance_config
    del instance_config
except ImportError:
    pass


CFG_MEMBERS_DICT = {
    'Canada': 'CAN',
    'Lithuania': 'LTU',
    'Ethiopia': 'ETH',
    'Argentina': 'ARG',
    'Bolivia': 'BOL',
    'Cameroon': 'CMR',
    'Burkina Faso': 'BFA',
    'Ghana': 'GHA',
    'Saudi Arabia': 'SAU',
    'Slovenia': 'SVN',
    'Guatemala': 'GTM',
    'Bosnia and Herzegovina': 'BIH',
    'Russian Federation': 'RUS',
    'Germany': 'DEU',
    'Spain': 'ESP',
    'International Centre for Scientific and Technical Information (ICSTI)': 'ICSTI',
    'Netherlands': 'NLD',
    'Oman': 'OMN',
    'Tanzania': 'TZA',
    'European Commission (EC)': 'EC',
    'Gabon': 'GAB',
    'African Union (AU)': 'AU',
    'New Zealand': 'NZL',
    'Yemen': 'YEM',
    'Pakistan': 'PAK',
    'Albania': 'ALB',
    'Middle Eastern Radioisotope Centre for the Arab Countries (MERRCAC)': 'MERRCAC',
    'United Arab Emirates (UAE)': 'ARE',
    "C\xc3\xb4te d'Ivoire": 'CIV',
    'India': 'IND',
    'Azerbaijan': 'AZE',
    'Food and Agricultural Organization of the United Nations (FAO)': 'FAO',
    'Kenya': 'KEN',
    'Tajikistan': 'TJK',
    'Arab Atomic Energy Agency (AAEA)': 'AAEA',
    'Turkey': 'TUR',
    'Afghanistan': 'AFG',
    'Provisional Technical Secretariat of the Preparatory Commission for the Comprehensive Nuclear-Test-Ban Treaty Organization (CTBTO)': 'CTBTO',
    'Bangladesh': 'BGD',
    'Synchrotron-light for Experimental Science and Applications in the Middle East (SESAME)': 'SESAME',
    'Viet Nam': 'VNM',
    'Mongolia': 'MNG',
    'France': 'FRA',
    'Syrian Arab Republic': 'SYR',
    'Peru': 'PER',
    'Norway': 'NOR',
    'Benin': 'BEN',
    'Korea': 'PRK',
    'World Meteorological Organization (WMO)': 'WMO',
    'Cuba': 'CUB',
    'International Commission on Radiological Protection (ICRP)': 'ICRP',
    'World Energy Council (WEC)': 'WEC',
    'China': 'CHN',
    'Armenia': 'ARM',
    'Ukraine': 'UKR',
    'Finland': 'FIN',
    'Libya': 'LBY',
    'Indonesia': 'IDN',
    'Central African Republic': 'CAF',
    'International Atomic Energy Agency (IAEA)': 'IAEA',
    'Mauritius': 'MUS',
    'Sweden': 'SWE',
    'Belarus': 'BLR',
    'Mali': 'MLI',
    'Bulgaria': 'BGR',
    'United States of America (USA)': 'USA',
    'Romania': 'ROU',
    'Chad': 'TCD',
    'South Africa': 'ZAF',
    'Cyprus': 'CYP',
    'Qatar': 'QAT',
    'Malaysia': 'MYS',
    'Austria': 'AUT',
    'Mozambique': 'MOZ',
    'World Health Organization (WHO)': 'WHO',
    'Slovakia': 'SVK',
    'Japan': 'JPN',
    'Niger': 'NER',
    'Joint Institute for Nuclear Research (JINR)': 'JINR',
    'Brazil': 'BRA',
    'Kuwait': 'KWT',
    'Panama': 'PAN',
    'Costa Rica': 'CRI',
    'Luxembourg': 'LUX',
    'Ireland': 'IRL',
    'Nigeria': 'NGA',
    'Ecuador': 'ECU',
    'Czech Republic': 'CZE',
    'Australia': 'AUS',
    'Iran': 'IRN',
    'Algeria': 'DZA',
    'El Salvador': 'SLV',
    'Chile': 'CHL',
    'Belgium': 'BEL',
    'Thailand': 'THA',
    'Haiti': 'HTI',
    'Iraq': 'IRQ',
    'Georgia': 'GEO',
    'World Nuclear Assosiation (WNA)': 'WNA',
    'Denmark': 'DNK',
    'Philippines': 'PHL',
    'Moldova': 'MDA',
    'Morocco': 'MAR',
    'Croatia': 'HRV',
    'OECD/Nuclear Energy Agency (NEA)': 'NEA',
    'Switzerland': 'CHE',
    'International Organization for Standardization (ISO)': 'ISO',
    'Brazilian-Argentine Agency for Accounting and Control of Nuclear Materials (ABACC)': 'ABACC',
    'Portugal': 'PRT',
    'Estonia': 'EST',
    'Uruguay': 'URY',
    'World Council of Nuclear Workers (WONUC)': 'WONUC',
    'Lebanon': 'LBN',
    'Uzbekistan': 'UZB',
    'Tunisia': 'TUN',
    'Colombia': 'COL',
    'Nicaragua': 'NIC',
    'World Nuclear University (WNU)': 'WNU',
    'Madagascar': 'MDG',
    'Italy': 'ITA',
    'United Nations Industrial Development Organization (UNIDO)': 'UNIDO',
    'Sudan': 'SDN',
    'Democratic Republic of the Congo': 'COD',
    'Venezuela': 'VEN',
    'Israel': 'ISR',
    'Zambia': 'ZMB',
    'Senegal': 'SEN',
    'Zimbabwe': 'ZWE',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Poland': 'POL',
    'Mauritania': 'MRT',
    'Kyrgyzstan': 'KGZ',
    'Uganda': 'UGA',
    'Macedonia': 'MKD',
    'United Nations Scientific Committee on the Effects of Atomic Radiation (UNSCEAR)': 'UNSCEAR',
    'Sri Lanka': 'LKA',
    'Latvia': 'LVA',
    'Hungary': 'HUN',
    'Myanmar': 'MMR',
    'Mexico': 'MEX',
    'Egypt': 'EGY',
    'International Institute for Applied Systems Analysis (IIASA)': 'IIASA',
    'European Organization for Nuclear Research (CERN)': 'CERN',
    'Singapore': 'SGP',
    'Serbia': 'SRB',
    'United Kingdom (UK)': 'GBR',
    'Greece': 'GRC',
    'Paraguay': 'PRY',
    'Namibia': 'NAM',
    'Botswana': 'BWA'}

CFG_MEMBERS_NAMES = CFG_MEMBERS_DICT.keys()
CFG_MEMBERS_CODES = CFG_MEMBERS_DICT.values()
